BlqhLesson05Model/BlqhLesson05/Models/DataModels/BlqhMember.cs
namespace BlqhLesson05.Models.DataModels
{
    public class BlqhMember
    {
        public string BlqhMemberId { get; set; }
        public string BlqhUserName { get; set; }
        public string BlqhPassword { get; set; }
        public string BlqhFullname { get; set; }
        public string BlqhEmail { get; set; }
    }
}

BlqhLesson05Model/BlqhLesson05/Models/ErrorViewModel.cs
namespace BlqhLesson05.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BlqhLesson05Model/BlqhLesson05/Controllers/BlqhHomeController.cs
using System.Diagnostics;
using BlqhLesson05.Models;
using BlqhLesson05.Models.DataModels;
using Microsoft.AspNetCore.Mvc;

namespace BlqhLesson05.Controllers
{
    public class BlqhHomeController : Controller
    {
        private readonly ILogger<BlqhHomeController> _logger;

        public BlqhHomeController(ILogger<BlqhHomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult BlqhIndex()
        {
            return View();
        }

        public IActionResult BlqhAbout()
        {
            BlqhMember blqhMember = new BlqhMember();
            blqhMember.BlqhMemberId = Guid.NewGuid().ToString();
            blqhMember.BlqhUserName = "BLQHung";
            blqhMember.BlqhPassword = "12345";
            blqhMember.BlqhFullname = "Bui Le Quoc Hung";
            blqhMember.BlqhEmail = "quochungb3@gmail.com";
            return View(blqhMember);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BlqhLesson05Model/BlqhLesson05/Controllers/BlqhMemberController.cs
using BlqhLesson05.Models.DataModels;
using Microsoft.AspNetCore.Mvc;

namespace BlqhLesson05.Controllers
{
    public class BlqhMemberController : Controller
    {
        private static List<BlqhMember> blqhListMembers = new List<BlqhMember>()
        {
            new BlqhMember {
                        BlqhMemberId = "2310900043",
                        BlqhUserName = "BLQHung",
                        BlqhPassword = "pass1",
                        BlqhFullname = "Bùi Lê Quốc Hùng",
                        BlqhEmail = "quochungb3@gmail.com"
                    },
            new BlqhMember{
                        BlqhMemberId = "2",
                        BlqhUserName = "user2",
                        BlqhPassword = "pass2",
                        BlqhFullname = "Nguyen Van A",
                        BlqhEmail = "user2@example.com"
                    },
            new BlqhMember{
                        BlqhMemberId = "3",
                        BlqhUserName = "user3",
                        BlqhPassword = "pass3",
                        BlqhFullname = "Nguyen Van B",
                        BlqhEmail = "user3@example.com"
                    },
             new BlqhMember{
                        BlqhMemberId = "4",
                        BlqhUserName = "user4",
                        BlqhPassword = "pass4",
                        BlqhFullname = "Nguyen Van C",
                        BlqhEmail = "user4@example.com"
                    },
             new BlqhMember {
                        BlqhMemberId = "5",
                        BlqhUserName = "user5",
                        BlqhPassword = "pass5",
                        BlqhFullname = "Nguyen Van C",
                        BlqhEmail = "user5@example@gmail.com"
                    }
        };
        public IActionResult BlqhIndex() //list member
        {
            return View(blqhListMembers);
        }
    }
}

BlqhLesson05Model/BlqhLesson05/Views/BlqhHome/BlqhAbout.cshtml
@{
    ViewData["Title"] = "Thong Tin Sinh Vien";
}
<div class="alert alert-info">
    <h1>@ViewData["Title"]</h1>
    <hr/>
    <p>Member id :@Model.BlqhMemberId</p>
    <p>Member UserName :@Model.BlqhUserName</p>
    <p>Member Pass :@Model.BlqhPassword</p>
    <p>Member FullName :@Model.BlqhFullname<p>
    <p>Member Email :@Model.BlqhEmail<p>
</div>

BlqhLesson05Model/BlqhLesson05/Views/BlqhHome/BlqhIndex.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome Bui Le Quoc Hung</h1>
    
</div>

BlqhLesson05Model/BlqhLesson05/Views/BlqhMember/BlqhIndex.cshtml
@model IEnumerable<BlqhLesson05.Models.DataModels.BlqhMember>
@{
    ViewData["Title"] = "BlqhIndex";
}

<h1> Danh Sach member</h1>
<table class=" table table-bordered table-hover">
    <thead>
        <tr>
            <th>Member ID</th>
            <th>Member UserName</th>
            <th>Member PassWord</th>
            <th>Member Fullname</th>
            <th>Member Email</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var blqhItem in Model)
        {
            <tr>
                <td>@blqhItem.BlqhMemberId</td>
                <td>@blqhItem.BlqhUserName</td>
                <td>@blqhItem.BlqhPassword</td>
                <td>@blqhItem.BlqhFullname</td>
                <td>@blqhItem.BlqhEmail</td>
            </tr>
        }
    </tbody>
</table>

BlqhLesson05Model/BlqhLesson05/Views/Shared/_BlqhLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlqhLesson05</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlqhLesson05.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        @Html.Partial("_BlqhNavBar")
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - BlqhLesson05 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BlqhLesson05Model/BlqhLesson05/Views/Shared/_BlqhNavBar.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="BlqhHome" asp-action="BlqhIndex">BlqhLesson05
            - Bui Le Quoc Hung
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="BlqhHome" asp-action="BlqhIndex">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="BlqhHome" asp-action="BlqhAbout">Thong Tin Sinh Vien</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="BlqhMember" asp-action="BlqhIndex">Danh Sach Sinh Vien</a>
                </li>
            </ul>
        </div>
    </div>
</nav>